default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: admin
  password: zxc123
  host: localhost

development:
  <<: *default
  database: gestor_imob_development

test:
  <<: *default
  database: gestor_imob_test

production:
  <<: *default
  database: gestor_imob_production
  username: gestor_imob
  password: <%= ENV["GESTOR_IMOB_DATABASE_PASSWORD"] %>
